import { create } from 'zustand'
import type { Conversation } from '@/types/mescli'
import { isDefaultTitle } from '@/utils/conversationTitle'

export type ConversationTitleStateType = 'default' | 'auto' | 'manual'

interface ConversationTitleState {
  /** 用户手动编辑过标题的会话 ID 集合 */
  manuallyEditedIds: Set<number>
  /** 自动生成标题的会话 ID 集合 */
  autoGeneratedIds: Set<number>
  /** 已尝试过自动刷新标题的会话 ID 集合 */
  autoRefreshAttemptedIds: Set<number>

  /** 标记某会话标题已被用户手动编辑 */
  markManuallyEdited: (conversationId: number) => void
  /** 标记某会话标题已被自动生成 */
  markAutoGenerated: (conversationId: number) => void
  /** 标记某会话已尝试过自动刷新标题 */
  markAutoRefreshAttempted: (conversationId: number) => void
  /** 判断某会话是否已尝试过自动刷新标题 */
  hasAutoRefreshAttempted: (conversationId: number) => boolean
  /** 清除某会话的标题状态 */
  clear: (conversationId: number) => void
  /** 删除会话时清理其标题状态 */
  removeConversation: (conversationId: number) => void
  /** 判断某会话标题是否被手动编辑过 */
  isManuallyEdited: (conversationId: number) => boolean
  /** 判断某会话标题是否被自动生成过 */
  isAutoGenerated: (conversationId: number) => boolean
  /** 根据当前标题判断标题状态：默认 / 自动生成 / 手动编辑 */
  getTitleState: (conversationId: number, currentTitle?: string | null) => ConversationTitleStateType
  /** 从会话列表同步标题状态（清理已不存在的会话、识别默认标题） */
  syncFromConversations: (conversations: Conversation[]) => void
}

export const useConversationTitleStore = create<ConversationTitleState>((set, get) => ({
  manuallyEditedIds: new Set(),
  autoGeneratedIds: new Set(),
  autoRefreshAttemptedIds: new Set(),

  markManuallyEdited: (conversationId: number) => {
    set((state) => {
      const next = new Set(state.manuallyEditedIds)
      next.add(conversationId)
      const autoNext = new Set(state.autoGeneratedIds)
      autoNext.delete(conversationId)
      return { manuallyEditedIds: next, autoGeneratedIds: autoNext }
    })
  },

  markAutoGenerated: (conversationId: number) => {
    set((state) => {
      const next = new Set(state.autoGeneratedIds)
      next.add(conversationId)
      return { autoGeneratedIds: next }
    })
  },

  markAutoRefreshAttempted: (conversationId: number) => {
    set((state) => {
      const next = new Set(state.autoRefreshAttemptedIds)
      next.add(conversationId)
      return { autoRefreshAttemptedIds: next }
    })
  },

  hasAutoRefreshAttempted: (conversationId: number) => {
    return get().autoRefreshAttemptedIds.has(conversationId)
  },

  clear: (conversationId: number) => {
    set((state) => {
      const manualNext = new Set(state.manuallyEditedIds)
      manualNext.delete(conversationId)
      const autoNext = new Set(state.autoGeneratedIds)
      autoNext.delete(conversationId)
      const refreshNext = new Set(state.autoRefreshAttemptedIds)
      refreshNext.delete(conversationId)
      return {
        manuallyEditedIds: manualNext,
        autoGeneratedIds: autoNext,
        autoRefreshAttemptedIds: refreshNext,
      }
    })
  },

  removeConversation: (conversationId: number) => {
    get().clear(conversationId)
  },

  isManuallyEdited: (conversationId: number) => {
    return get().manuallyEditedIds.has(conversationId)
  },

  isAutoGenerated: (conversationId: number) => {
    return get().autoGeneratedIds.has(conversationId)
  },

  getTitleState: (conversationId: number, currentTitle?: string | null): ConversationTitleStateType => {
    if (get().manuallyEditedIds.has(conversationId)) return 'manual'
    if (get().autoGeneratedIds.has(conversationId)) return 'auto'
    if (isDefaultTitle(currentTitle)) return 'default'
    // 标题非默认且未被显式标记，保守视为手动编辑
    return 'manual'
  },

  syncFromConversations: (conversations: Conversation[]) => {
    const validIds = new Set(conversations.map((c) => c.id))
    set((state) => {
      const cleanup = (set: Set<number>) => {
        const next = new Set(set)
        for (const id of next) {
          if (!validIds.has(id)) next.delete(id)
        }
        return next
      }
      return {
        manuallyEditedIds: cleanup(state.manuallyEditedIds),
        autoGeneratedIds: cleanup(state.autoGeneratedIds),
        autoRefreshAttemptedIds: cleanup(state.autoRefreshAttemptedIds),
      }
    })
  },
}))
